services:
  app-dev:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/workspace
      - cargo-target:/.rust/target
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - /workspace/.pnpm-store
      - /workspace/node_modules
      - /workspace/share/protobuf/node_modules
      - /workspace/app/frontend/node_modules
      - /workspace/target

    ports:
      - "3333:3333"
      - "8788:8788"
      - "8787:8787"
    env_file:
      - ./develop/.env
    working_dir: /workspace
    tty: true
volumes:
  cargo-target:
